from pymongo.write_concern import WriteConcern
from pymodm import MongoModel, fields


# 日历
class TradeDays(MongoModel):
    exchange = fields.CharField(blank=True)
    cal_date = fields.IntegerField(primary_key=True)
    is_open = fields.IntegerField(blank=True)

    class Meta:
        write_concern = WriteConcern(j=True)
        connection_alias = 'trade_days'
        final = True


# 原始行情数据
class OriginDailyBar(MongoModel):
    ts_code = fields.CharField(blank=True)
    trade_date = fields.IntegerField(blank=True)
    open = fields.FloatField(blank=True)
    high = fields.FloatField(blank=True)
    low = fields.FloatField(blank=True)
    close = fields.FloatField(blank=True)
    pre_close = fields.FloatField(blank=True)
    change = fields.FloatField(blank=True)
    pct_chg = fields.FloatField(blank=True)
    vol = fields.FloatField(blank=True)
    amount = fields.FloatField(blank=True)
    key = fields.CharField(primary_key=True)

    class Meta:
        write_concern = WriteConcern(j=True)
        connection_alias = 'origin_daily_bar'
        final = True


# 复权因子
class AdjustFactor(MongoModel):
    ts_code = fields.CharField(blank=True)
    trade_date = fields.IntegerField(blank=True)
    adj_factor = fields.FloatField(blank=True)
    key = fields.CharField(primary_key=True)

    class Meta:
        write_concern = WriteConcern(j=True)
        connection_alias = 'adjust_factor'
        final = True


# 上市公司基本信息
class StocksMain(MongoModel):
    ts_code = fields.CharField(primary_key=True)
    exchange = fields.CharField(blank=True)
    chairman = fields.CharField(blank=True)
    manager = fields.CharField(blank=True)
    secretary = fields.CharField(blank=True)
    reg_capital = fields.FloatField(blank=True)
    setup_date = fields.CharField(blank=True)
    province = fields.CharField(blank=True)
    city = fields.CharField(blank=True)
    website = fields.CharField(blank=True)
    email = fields.CharField(blank=True)
    empluyees = fields.IntegerField(blank=True)

    class Meta:
        write_concern = WriteConcern(j=True)
        connection_alias = 'stock_main'
        final = True


# 股票名单
class StockList(MongoModel):
    ts_code = fields.CharField(primary_key=True)
    name = fields.CharField(blank=True)
    area = fields.CharField(blank=True)
    industry = fields.CharField(blank=True)
    exchange = fields.CharField(blank=True)
    list_status = fields.CharField(blank=True)
    list_date = fields.CharField(blank=True)
    delist_date = fields.CharField(blank=True)
    is_hs = fields.CharField(blank=True)

    class Meta:
        write_concern = WriteConcern(j=True)
        connection_alias = 'stock_list'
        final = True


# 停牌信息
class SuspendList(MongoModel):
    ts_code = fields.CharField(blank=True)
    suspend_date = fields.CharField(blank=True)
    resume_date = fields.CharField(blank=True)
    suspend_reason = fields.CharField(blank=True)
    key = fields.CharField(primary_key=True)

    class Meta:
        write_concern = WriteConcern(j=True)
        connection_alias = 'suspend_list'
        final = True


# 每日指标
class Daily(MongoModel):
    ts_code = fields.CharField(blank=True)
    trade_date = fields.IntegerField(blank=True)
    close = fields.FloatField(blank=True)
    turnover_rate = fields.FloatField(blank=True)
    turnover_rate_f = fields.FloatField(blank=True)
    volume_ratio = fields.FloatField(blank=True)
    pe = fields.FloatField(blank=True)
    pe_ttm = fields.FloatField(blank=True)
    pb = fields.FloatField(blank=True)
    ps = fields.FloatField(blank=True)
    ps_ttm = fields.FloatField(blank=True)
    total_share = fields.FloatField(blank=True)
    float_share = fields.FloatField(blank=True)
    free_share = fields.FloatField(blank=True)
    total_mv = fields.FloatField(blank=True)
    circ_mv = fields.FloatField(blank=True)
    key = fields.CharField(primary_key=True)

    class Meta:
        write_concern = WriteConcern(j=True)
        connection_alias = 'daily'
        final = True


class IncomeSheet(MongoModel):
    ts_code = fields.CharField(blank=True)
    ann_date = fields.CharField(blank=True)
    f_ann_date = fields.CharField(blank=True)
    end_date = fields.CharField(blank=True)
    report_type = fields.CharField(blank=True)
    comp_type = fields.CharField(blank=True)
    basic_eps = fields.FloatField(blank=True)
    diluted_eps = fields.FloatField(blank=True)
    total_revenue = fields.FloatField(blank=True)
    revenue = fields.FloatField(blank=True)
    int_income = fields.FloatField(blank=True)
    prem_earned = fields.FloatField(blank=True)
    comm_income = fields.FloatField(blank=True)
    n_commis_income = fields.FloatField(blank=True)
    n_oth_income = fields.FloatField(blank=True)
    n_oth_b_income = fields.FloatField(blank=True)
    prem_income = fields.FloatField(blank=True)
    out_prem = fields.FloatField(blank=True)
    une_prem_reser = fields.FloatField(blank=True)
    reins_income = fields.FloatField(blank=True)
    n_sec_tb_income = fields.FloatField(blank=True)
    n_sec_uw_income = fields.FloatField(blank=True)
    n_asset_mg_income = fields.FloatField(blank=True)
    oth_b_income = fields.FloatField(blank=True)
    fv_value_chg_gain = fields.FloatField(blank=True)
    invest_income = fields.FloatField(blank=True)
    ass_invest_income = fields.FloatField(blank=True)
    forex_gain = fields.FloatField(blank=True)
    total_cogs = fields.FloatField(blank=True)
    oper_cost = fields.FloatField(blank=True)
    int_exp = fields.FloatField(blank=True)
    comm_exp = fields.FloatField(blank=True)
    biz_tax_surchg = fields.FloatField(blank=True)
    sell_exp = fields.FloatField(blank=True)
    admin_exp = fields.FloatField(blank=True)
    fin_exp = fields.FloatField(blank=True)
    assets_impair_loss = fields.FloatField(blank=True)
    prem_refund = fields.FloatField(blank=True)
    compens_payout = fields.FloatField(blank=True)
    reser_insur_liab = fields.FloatField(blank=True)
    div_payt = fields.FloatField(blank=True)
    reins_exp = fields.FloatField(blank=True)
    oper_exp = fields.FloatField(blank=True)
    compens_payout_refu = fields.FloatField(blank=True)
    insur_reser_refu = fields.FloatField(blank=True)
    reins_cost_refund = fields.FloatField(blank=True)
    other_bus_cost = fields.FloatField(blank=True)
    operate_profit = fields.FloatField(blank=True)
    non_oper_income = fields.FloatField(blank=True)
    non_oper_exp = fields.FloatField(blank=True)
    nca_disploss = fields.FloatField(blank=True)
    total_profit = fields.FloatField(blank=True)
    income_tax = fields.FloatField(blank=True)
    n_income = fields.FloatField(blank=True)
    n_income_attr_p = fields.FloatField(blank=True)
    minority_gain = fields.FloatField(blank=True)
    oth_compr_income = fields.FloatField(blank=True)
    t_compr_income = fields.FloatField(blank=True)
    compr_inc_attr_p = fields.FloatField(blank=True)
    compr_inc_attr_m_s = fields.FloatField(blank=True)
    ebit = fields.FloatField(blank=True)
    ebitda = fields.FloatField(blank=True)
    insurance_exp = fields.FloatField(blank=True)
    undist_profit = fields.FloatField(blank=True)
    distable_profit = fields.FloatField(blank=True)
    key = fields.CharField(primary_key=True)

    class Meta:
        write_concern = WriteConcern(j=True)
        connection_alias = 'income_sheet'
        final = True


class BalanceSheet(MongoModel):
    ts_code = fields.CharField(blank=True)
    ann_date = fields.CharField(blank=True)
    f_ann_date = fields.CharField(blank=True)
    end_date = fields.CharField(blank=True)
    report_type = fields.CharField(blank=True)
    comp_type = fields.CharField(blank=True)
    total_share = fields.FloatField(blank=True)
    cap_rese = fields.FloatField(blank=True)
    undistr_porfit = fields.FloatField(blank=True)
    surplus_rese = fields.FloatField(blank=True)
    special_rese = fields.FloatField(blank=True)
    money_cap = fields.FloatField(blank=True)
    trad_asset = fields.FloatField(blank=True)
    notes_receiv = fields.FloatField(blank=True)
    accounts_receiv = fields.FloatField(blank=True)
    oth_receiv = fields.FloatField(blank=True)
    prepayment = fields.FloatField(blank=True)
    div_receiv = fields.FloatField(blank=True)
    int_receiv = fields.FloatField(blank=True)
    inventories = fields.FloatField(blank=True)
    amor_exp = fields.FloatField(blank=True)
    nca_within_1y = fields.FloatField(blank=True)
    sett_rsrv = fields.FloatField(blank=True)
    loanto_oth_bank_fi = fields.FloatField(blank=True)
    premium_receiv = fields.FloatField(blank=True)
    reinsur_receiv = fields.FloatField(blank=True)
    reinsur_res_receiv = fields.FloatField(blank=True)
    pur_resale_fa = fields.FloatField(blank=True)
    oth_cur_assets = fields.FloatField(blank=True)
    total_cur_assets = fields.FloatField(blank=True)
    fa_avail_for_sale = fields.FloatField(blank=True)
    htm_invest = fields.FloatField(blank=True)
    lt_eqt_invest = fields.FloatField(blank=True)
    invest_real_estate = fields.FloatField(blank=True)
    time_deposits = fields.FloatField(blank=True)
    oth_assets = fields.FloatField(blank=True)
    lt_rec = fields.FloatField(blank=True)
    fix_assets = fields.FloatField(blank=True)
    cip = fields.FloatField(blank=True)
    const_materials = fields.FloatField(blank=True)
    fixed_assets_disp = fields.FloatField(blank=True)
    produc_bio_assets = fields.FloatField(blank=True)
    oil_and_gas_assets = fields.FloatField(blank=True)
    intan_assets = fields.FloatField(blank=True)
    r_and_d = fields.FloatField(blank=True)
    goodwill = fields.FloatField(blank=True)
    lt_amor_exp = fields.FloatField(blank=True)
    defer_tax_assets = fields.FloatField(blank=True)
    decr_in_disbur = fields.FloatField(blank=True)
    oth_nca = fields.FloatField(blank=True)
    total_nca = fields.FloatField(blank=True)
    cash_reser_cb = fields.FloatField(blank=True)
    depos_in_oth_bfi = fields.FloatField(blank=True)
    prec_metals = fields.FloatField(blank=True)
    deriv_assets = fields.FloatField(blank=True)
    rr_reins_une_prem = fields.FloatField(blank=True)
    rr_reins_outstd_cla = fields.FloatField(blank=True)
    rr_reins_lins_liab = fields.FloatField(blank=True)
    rr_reins_lthins_liab = fields.FloatField(blank=True)
    refund_depos = fields.FloatField(blank=True)
    ph_pledge_loans = fields.FloatField(blank=True)
    refund_cap_depos = fields.FloatField(blank=True)
    indep_acct_assets = fields.FloatField(blank=True)
    client_depos = fields.FloatField(blank=True)
    client_prov = fields.FloatField(blank=True)
    transac_seat_fee = fields.FloatField(blank=True)
    invest_as_receiv = fields.FloatField(blank=True)
    total_assets = fields.FloatField(blank=True)
    lt_borr = fields.FloatField(blank=True)
    st_borr = fields.FloatField(blank=True)
    cb_borr = fields.FloatField(blank=True)
    depos_ib_deposits = fields.FloatField(blank=True)
    loan_oth_bank = fields.FloatField(blank=True)
    trading_fl = fields.FloatField(blank=True)
    notes_payable = fields.FloatField(blank=True)
    acct_payable = fields.FloatField(blank=True)
    adv_receipts = fields.FloatField(blank=True)
    sold_for_repur_fa = fields.FloatField(blank=True)
    comm_payable = fields.FloatField(blank=True)
    payroll_payable = fields.FloatField(blank=True)
    taxes_payable = fields.FloatField(blank=True)
    int_payable = fields.FloatField(blank=True)
    div_payable = fields.FloatField(blank=True)
    oth_payable = fields.FloatField(blank=True)
    acc_exp = fields.FloatField(blank=True)
    deferred_inc = fields.FloatField(blank=True)
    st_bonds_payable = fields.FloatField(blank=True)
    payable_to_reinsurer = fields.FloatField(blank=True)
    rsrv_insur_cont = fields.FloatField(blank=True)
    acting_trading_sec = fields.FloatField(blank=True)
    acting_uw_sec = fields.FloatField(blank=True)
    non_cur_liab_due_1y = fields.FloatField(blank=True)
    oth_cur_liab = fields.FloatField(blank=True)
    total_cur_liab = fields.FloatField(blank=True)
    bond_payable = fields.FloatField(blank=True)
    lt_payable = fields.FloatField(blank=True)
    specific_payables = fields.FloatField(blank=True)
    estimated_liab = fields.FloatField(blank=True)
    defer_tax_liab = fields.FloatField(blank=True)
    defer_inc_non_cur_liab = fields.FloatField(blank=True)
    oth_ncl = fields.FloatField(blank=True)
    total_ncl = fields.FloatField(blank=True)
    depos_oth_bfi = fields.FloatField(blank=True)
    deriv_liab = fields.FloatField(blank=True)
    depos = fields.FloatField(blank=True)
    agency_bus_liab = fields.FloatField(blank=True)
    oth_liab = fields.FloatField(blank=True)
    prem_receiv_adva = fields.FloatField(blank=True)
    depos_received = fields.FloatField(blank=True)
    ph_invest = fields.FloatField(blank=True)
    reser_une_prem = fields.FloatField(blank=True)
    reser_outstd_claims = fields.FloatField(blank=True)
    reser_lins_liab = fields.FloatField(blank=True)
    reser_lthins_liab = fields.FloatField(blank=True)
    indept_acc_liab = fields.FloatField(blank=True)
    pledge_borr = fields.FloatField(blank=True)
    indem_payable = fields.FloatField(blank=True)
    policy_div_payable = fields.FloatField(blank=True)
    total_liab = fields.FloatField(blank=True)
    treasury_share = fields.FloatField(blank=True)
    ordin_risk_reser = fields.FloatField(blank=True)
    forex_differ = fields.FloatField(blank=True)
    invest_loss_unconf = fields.FloatField(blank=True)
    minority_int = fields.FloatField(blank=True)
    total_hldr_eqy_exc_min_int = fields.FloatField(blank=True)
    total_hldr_eqy_inc_min_int = fields.FloatField(blank=True)
    total_liab_hldr_eqy = fields.FloatField(blank=True)
    lt_payroll_payable = fields.FloatField(blank=True)
    oth_comp_income = fields.FloatField(blank=True)
    oth_eqt_tools = fields.FloatField(blank=True)
    oth_eqt_tools_p_shr = fields.FloatField(blank=True)
    lending_funds = fields.FloatField(blank=True)
    acc_receivable = fields.FloatField(blank=True)
    st_fin_payable = fields.FloatField(blank=True)
    payables = fields.FloatField(blank=True)
    hfs_assets = fields.FloatField(blank=True)
    hfs_sales = fields.FloatField(blank=True)
    key = fields.CharField(primary_key=True)

    class Meta:
        write_concern = WriteConcern(j=True)
        connection_alias = 'balance_sheet'
        final = True


class CashFlowSheet(MongoModel):
    ts_code = fields.CharField(blank=True)
    ann_date = fields.CharField(blank=True)
    f_ann_date = fields.CharField(blank=True)
    end_date = fields.CharField(blank=True)
    comp_type = fields.CharField(blank=True)
    report_type = fields.CharField(blank=True)
    net_profit = fields.FloatField(blank=True)
    finan_exp = fields.FloatField(blank=True)
    c_fr_sale_sg = fields.FloatField(blank=True)
    recp_tax_rends = fields.FloatField(blank=True)
    n_depos_incr_fi = fields.FloatField(blank=True)
    n_incr_loans_cb = fields.FloatField(blank=True)
    n_inc_borr_oth_fi = fields.FloatField(blank=True)
    prem_fr_orig_contr = fields.FloatField(blank=True)
    n_incr_insured_dep = fields.FloatField(blank=True)
    n_reinsur_prem = fields.FloatField(blank=True)
    n_incr_disp_tfa = fields.FloatField(blank=True)
    ifc_cash_incr = fields.FloatField(blank=True)
    n_incr_disp_faas = fields.FloatField(blank=True)
    n_incr_loans_oth_bank = fields.FloatField(blank=True)
    n_cap_incr_repur = fields.FloatField(blank=True)
    c_fr_oth_operate_a = fields.FloatField(blank=True)
    c_inf_fr_operate_a = fields.FloatField(blank=True)
    c_paid_goods_s = fields.FloatField(blank=True)
    c_paid_to_for_empl = fields.FloatField(blank=True)
    c_paid_for_taxes = fields.FloatField(blank=True)
    n_incr_clt_loan_adv = fields.FloatField(blank=True)
    n_incr_dep_cbob = fields.FloatField(blank=True)
    c_pay_claims_orig_inco = fields.FloatField(blank=True)
    pay_handling_chrg = fields.FloatField(blank=True)
    pay_comm_insur_plcy = fields.FloatField(blank=True)
    oth_cash_pay_oper_act = fields.FloatField(blank=True)
    st_cash_out_act = fields.FloatField(blank=True)
    n_cashflow_act = fields.FloatField(blank=True)
    oth_recp_ral_inv_act = fields.FloatField(blank=True)
    c_disp_withdrwl_invest = fields.FloatField(blank=True)
    c_recp_return_invest = fields.FloatField(blank=True)
    n_recp_disp_fiolta = fields.FloatField(blank=True)
    n_recp_disp_sobu = fields.FloatField(blank=True)
    stot_inflows_inv_act = fields.FloatField(blank=True)
    c_pay_acq_const_fiolta = fields.FloatField(blank=True)
    c_paid_invest = fields.FloatField(blank=True)
    n_disp_subs_oth_biz = fields.FloatField(blank=True)
    oth_pay_ral_inv_act = fields.FloatField(blank=True)
    n_incr_pledge_loan = fields.FloatField(blank=True)
    stot_out_inv_act = fields.FloatField(blank=True)
    n_cashflow_inv_act = fields.FloatField(blank=True)
    c_recp_borrow = fields.FloatField(blank=True)
    proc_issue_bonds = fields.FloatField(blank=True)
    oth_cash_recp_ral_fnc_act = fields.FloatField(blank=True)
    stot_cash_in_fnc_act = fields.FloatField(blank=True)
    free_cashflow = fields.FloatField(blank=True)
    c_prepay_amt_borr = fields.FloatField(blank=True)
    c_pay_dist_dpcp_int_exp = fields.FloatField(blank=True)
    incl_dvd_profit_paid_sc_ms = fields.FloatField(blank=True)
    oth_cashpay_ral_fnc_act = fields.FloatField(blank=True)
    stot_cashout_fnc_act = fields.FloatField(blank=True)
    n_cash_flows_fnc_act = fields.FloatField(blank=True)
    eff_fx_flu_cash = fields.FloatField(blank=True)
    n_incr_cash_cash_equ = fields.FloatField(blank=True)
    c_cash_equ_beg_period = fields.FloatField(blank=True)
    c_cash_equ_end_period = fields.FloatField(blank=True)
    c_recp_cap_contrib = fields.FloatField(blank=True)
    incl_cash_rec_saims = fields.FloatField(blank=True)
    uncon_invest_loss = fields.FloatField(blank=True)
    prov_depr_assets = fields.FloatField(blank=True)
    depr_fa_coga_dpba = fields.FloatField(blank=True)
    amort_intang_assets = fields.FloatField(blank=True)
    lt_amort_deferred_exp = fields.FloatField(blank=True)
    decr_deferred_exp = fields.FloatField(blank=True)
    incr_acc_exp = fields.FloatField(blank=True)
    loss_disp_fiolta = fields.FloatField(blank=True)
    loss_scr_fa = fields.FloatField(blank=True)
    loss_fv_chg = fields.FloatField(blank=True)
    invest_loss = fields.FloatField(blank=True)
    decr_def_inc_tax_assets = fields.FloatField(blank=True)
    incr_def_inc_tax_liab = fields.FloatField(blank=True)
    decr_inventories = fields.FloatField(blank=True)
    decr_oper_payable = fields.FloatField(blank=True)
    incr_oper_payable = fields.FloatField(blank=True)
    others = fields.FloatField(blank=True)
    im_net_cashflow_oper_act = fields.FloatField(blank=True)
    conv_debt_into_cap = fields.FloatField(blank=True)
    conv_copbonds_due_within_1y = fields.FloatField(blank=True)
    fa_fnc_leases = fields.FloatField(blank=True)
    end_bal_cash = fields.FloatField(blank=True)
    beg_bal_cash = fields.FloatField(blank=True)
    end_bal_cash_equ = fields.FloatField(blank=True)
    beg_bal_cash_equ = fields.FloatField(blank=True)
    im_n_incr_cash_equ = fields.FloatField(blank=True)
    key = fields.CharField(primary_key=True)

    class Meta:
        write_concern = WriteConcern(j=True)
        connection_alias = 'cashflow_sheet'
        final = True


class FinancialIndicator(MongoModel):
    ts_code = fields.CharField(blank=True)
    ann_date = fields.CharField(blank=True)
    end_date = fields.CharField(blank=True)
    eps = fields.FloatField(blank=True)
    dt_eps = fields.FloatField(blank=True)
    total_revenue_ps = fields.FloatField(blank=True)
    revenue_ps = fields.FloatField(blank=True)
    capital_rese_ps = fields.FloatField(blank=True)
    surplus_rese_ps = fields.FloatField(blank=True)
    undist_profit_ps = fields.FloatField(blank=True)
    extra_item = fields.FloatField(blank=True)
    profit_dedt = fields.FloatField(blank=True)
    gross_margin = fields.FloatField(blank=True)
    current_ratio = fields.FloatField(blank=True)
    quick_ratio = fields.FloatField(blank=True)
    cash_ratio = fields.FloatField(blank=True)
    ar_turn = fields.FloatField(blank=True)
    ca_turn = fields.FloatField(blank=True)
    fa_turn = fields.FloatField(blank=True)
    assets_turn = fields.FloatField(blank=True)
    op_income = fields.FloatField(blank=True)
    ebit = fields.FloatField(blank=True)
    ebitda = fields.FloatField(blank=True)
    fcff = fields.FloatField(blank=True)
    fcfe = fields.FloatField(blank=True)
    current_exint = fields.FloatField(blank=True)
    noncurrent_exint = fields.FloatField(blank=True)
    interestdebt = fields.FloatField(blank=True)
    netdebt = fields.FloatField(blank=True)
    tangible_asset = fields.FloatField(blank=True)
    working_capital = fields.FloatField(blank=True)
    networking_capital = fields.FloatField(blank=True)
    invest_capital = fields.FloatField(blank=True)
    retained_earnings = fields.FloatField(blank=True)
    diluted2_eps = fields.FloatField(blank=True)
    bps = fields.FloatField(blank=True)
    ocfps = fields.FloatField(blank=True)
    retainedps = fields.FloatField(blank=True)
    cfps = fields.FloatField(blank=True)
    ebit_ps = fields.FloatField(blank=True)
    fcff_ps = fields.FloatField(blank=True)
    fcfe_ps = fields.FloatField(blank=True)
    netprofit_margin = fields.FloatField(blank=True)
    grossprofit_margin = fields.FloatField(blank=True)
    cogs_of_sales = fields.FloatField(blank=True)
    expense_of_sales = fields.FloatField(blank=True)
    profit_to_gr = fields.FloatField(blank=True)
    saleexp_to_gr = fields.FloatField(blank=True)
    adminexp_of_gr = fields.FloatField(blank=True)
    finaexp_of_gr = fields.FloatField(blank=True)
    impai_ttm = fields.FloatField(blank=True)
    gc_of_gr = fields.FloatField(blank=True)
    op_of_gr = fields.FloatField(blank=True)
    ebit_of_gr = fields.FloatField(blank=True)
    roe = fields.FloatField(blank=True)
    roe_waa = fields.FloatField(blank=True)
    roe_dt = fields.FloatField(blank=True)
    roa = fields.FloatField(blank=True)
    npta = fields.FloatField(blank=True)
    roic = fields.FloatField(blank=True)
    roe_yearly = fields.FloatField(blank=True)
    roa2_yearly = fields.FloatField(blank=True)
    debt_to_assets = fields.FloatField(blank=True)
    assets_to_eqt = fields.FloatField(blank=True)
    dp_assets_to_eqt = fields.FloatField(blank=True)
    ca_to_assets = fields.FloatField(blank=True)
    nca_to_assets = fields.FloatField(blank=True)
    tbassets_to_totalassets = fields.FloatField(blank=True)
    int_to_talcap = fields.FloatField(blank=True)
    eqt_to_talcapital = fields.FloatField(blank=True)
    currentdebt_to_debt = fields.FloatField(blank=True)
    longdeb_to_debt = fields.FloatField(blank=True)
    ocf_to_shortdebt = fields.FloatField(blank=True)
    debt_to_eqt = fields.FloatField(blank=True)
    eqt_to_debt = fields.FloatField(blank=True)
    eqt_to_interestdebt = fields.FloatField(blank=True)
    tangibleasset_to_debt = fields.FloatField(blank=True)
    tangasset_to_intdebt = fields.FloatField(blank=True)
    tangibleasset_to_netdebt = fields.FloatField(blank=True)
    ocf_to_debt = fields.FloatField(blank=True)
    turn_days = fields.FloatField(blank=True)
    roa_yearly = fields.FloatField(blank=True)
    roa_dp = fields.FloatField(blank=True)
    fixed_assets = fields.FloatField(blank=True)
    profit_to_op = fields.FloatField(blank=True)
    q_saleexp_to_gr = fields.FloatField(blank=True)
    q_gc_to_gr = fields.FloatField(blank=True)
    q_roe = fields.FloatField(blank=True)
    q_dt_roe = fields.FloatField(blank=True)
    q_npta = fields.FloatField(blank=True)
    q_ocf_to_sales = fields.FloatField(blank=True)
    basic_eps_yoy = fields.FloatField(blank=True)
    dt_eps_yoy = fields.FloatField(blank=True)
    cfps_yoy = fields.FloatField(blank=True)
    op_yoy = fields.FloatField(blank=True)
    ebt_yoy = fields.FloatField(blank=True)
    netprofit_yoy = fields.FloatField(blank=True)
    dt_netprofit_yoy = fields.FloatField(blank=True)
    ocf_yoy = fields.FloatField(blank=True)
    roe_yoy = fields.FloatField(blank=True)
    bps_yoy = fields.FloatField(blank=True)
    assets_yoy = fields.FloatField(blank=True)
    eqt_yoy = fields.FloatField(blank=True)
    tr_yoy = fields.FloatField(blank=True)
    or_yoy = fields.FloatField(blank=True)
    q_sales_yoy = fields.FloatField(blank=True)
    q_op_qoq = fields.FloatField(blank=True)
    equity_yoy = fields.FloatField(blank=True)
    key = fields.CharField(primary_key=True)

    class Meta:
        write_concern = WriteConcern(j=True)
        connection_alias = 'financial_indicator'
        final = True


class IndexBar(MongoModel):
    ts_code = fields.CharField(blank=True)
    trade_date = fields.IntegerField(blank=True)
    close = fields.FloatField(blank=True)
    open = fields.FloatField(blank=True)
    high = fields.FloatField(blank=True)
    low = fields.FloatField(blank=True)
    pre_close = fields.FloatField(blank=True)
    change = fields.FloatField(blank=True)
    pct_chg = fields.FloatField(blank=True)
    vol = fields.FloatField(blank=True)
    amount = fields.FloatField(blank=True)
    key = fields.CharField(primary_key=True)

    class Meta:
        write_concern = WriteConcern(j=True)
        connection_alias = 'index_bar'
        final = True


class IndexWeight(MongoModel):
    index_code = fields.CharField(blank=True)
    con_code = fields.CharField(blank=True)
    trade_date = fields.CharField(blank=True)
    weight = fields.FloatField(blank=True)
    key = fields.CharField(primary_key=True)

    class Meta:
        write_concern = WriteConcern(j=True)
        connection_alias = 'index_weight'
        final = True